name: bund

description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  auto_route: ^7.8.4
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  get_it: ^7.6.4
  intl: ^0.19.0
  json_annotation: ^4.8.1
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  svg_flutter: ^0.0.1

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - lib/src/assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: lib/src/assets/fonts/lato/Lato-Thin.ttf
          weight: 100
        - asset: lib/src/assets/fonts/lato/Lato-Light.ttf
          weight: 300
        - asset: lib/src/assets/fonts/lato/Lato-Regular.ttf
          style: normal
        - asset: lib/src/assets/fonts/lato/Lato-Italic.ttf
          style: italic
        - asset: lib/src/assets/fonts/lato/Lato-Bold.ttf
          weight: 700
        - asset: lib/src/assets/fonts/lato/Lato-Black.ttf
          weight: 900
        - asset: lib/src/assets/fonts/lato/Lato-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: lib/src/assets/fonts/lato/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: lib/src/assets/fonts/lato/Lato-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: lib/src/assets/fonts/lato/Lato-BlackItalic.ttf
          weight: 900
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
